### PR TITLE
Upgrade to MoltenVK 1.1.0

### PR DESCRIPTION
**Pull request by repi**
This does work locally now, but unfortunately MoltenVK removed support for static linking in 1.1.0, only dynamic linking (and the new XCFramework "linking"?) is supported. Which sorta defeats the point of this crate which is built for static linking.

### CODE REVIEW

**Comment by repi** [comment]
Not sure why the tests are crashing on CI :( Must be some Mac OS / XCode / Framework mismatch somehow?

Does work locally for me, but I'm on Big Sur.

```
 2020-10-05 20:11:40.061 ash_molten-2f6fca259a1c716b[4404:26402] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff30044727 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff68f8ca9e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff30070ccc CFArrayExchangeValuesAtIndices + 0
	3   libMoltenVK.dylib                   0x0000000109c928e7 _ZN15MVKPixelFormatsC2EP17MVKPhysicalDevice + 535
	4   libMoltenVK.dylib                   0x000000010a00fbf7 _GLOBAL__sub_I_mvk_datatypes.mm + 23
	5   ???                                 0x00000001184461d3 0x0 + 4702101971
	6   ???                                 0x00000001184465de 0x0 + 4702103006
	7   ???                                 0x0000000118440ffb 0x0 + 4702081019
	8   ???                                 0x0000000118440f66 0x0 + 4702080870
	9   ???                                 0x000000011843f0b4 0x0 + 4702073012
	10  ???                                 0x000000011843f154 0x0 + 4702073172
	11  ???                                 0x000000011842d6a8 0x0 + 4702000808
	12  ???                                 0x0000000118432bba 0x0 + 4702022586
	13  ???                                 0x000000011842c227 0x0 + 4701995559
	14  ???                                 0x000000011842c025 0x0 + 4701995045
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by emilk** [comment]
I can also compile this branch locally

**Comment by repi** [comment]
Filed https://github.com/KhronosGroup/MoltenVK/issues/1122

**Comment by MarnixKuijs** [comment]
I spend some time looking into XCFrameworks and trying to figure out if we could directly use them to link with them. It seems however that rust/cargo as of now doesn't have support for it. "Linking" with an XCFramework is something only Xcode can do and doesn't have a command line interface as of now. An XCFramework is nothing more than a folder that contains static libs/frameworks for different platforms and a meta data file to look them up. For MoltenVK it just has static libs. So for now the best solution is just linking these static libs directly until rust/cargo gets support for XCFrameworks

**Comment by repi** [comment]
@MarnixKuijs that sounds like a fine workaround for this upgrade. Later for Mac on Apple Silicon support we'll likely still do separate builds for each target instead of a universal executable so even then the XCFramework may not be needed.

Know if there is a Rust/Cargo issue that one can link here for XCFramework support?

**Comment by MarnixKuijs** [comment]
> Know if there is a Rust/Cargo issue that one can link here for XCFramework support?
Currently none that I can find

**Comment by MarnixKuijs** [comment]
Seem CI can't find the lib, but it does compile locally for me.

**Comment by MarnixKuijs** [comment]
When it comes to the exception the problem why the CI fails has nothing to do with the code or the upgrade to MoltenVK 1.1.0. When downloading the artefacts from the CI and running them locally on my Mac it executes fine. So it seems to me that it has something to do with the machine that GitHub actions are performed on. Although it is strange considering the fact that zero test are being executed so I am even more confused on why it is even throwing an exception.

**Comment by MarnixKuijs** [comment]
Waiting on [pull request on MoltenVK](https://github.com/KhronosGroup/MoltenVK/pull/1142)

**Comment by MarnixKuijs** [comment]
https://github.com/KhronosGroup/MoltenVK/commit/d208f94788e4422cc8580e556ded7805da9f0925 uses features from MacOS 11+. So using the master/main branch of MoltenVK is not an option unless we force everybody to upgrade. We can't use the v1.1.0 branch because it will break our CI. This can be circumvented by instead of running cargo test we run cargo build. This wouldn't be a bad solution since zero test are being executed so cargo build and cargo test would basically be equivalent. Last option is to use my branch for the although this would halt us from getting any updates from MoltenVK. @repi any thoughts on this?

**Comment by repi** [comment]
I'm fine with just `cargo build` if that solves it

**Review by MarnixKuijs — APPROVED** [review]

**Comment by repi** [comment]
@MarnixKuijs nice work! tested locally and worked fine

**Pull request merged**
