### PR TITLE
Update Code Of Covenant to 2.0

### PR DESCRIPTION
**Pull request by XAMPPRocky**

### CODE REVIEW

**Review by repi — APPROVED** [review]

**Comment by XAMPPRocky** [comment]
The build failures here seem unrelated. It's the same error I was getting without using `pre-built`.

https://github.com/EmbarkStudios/ash-molten/pull/37/checks?check_run_id=1448122729#step:4:18

**Comment by MarnixKuijs** [comment]
reason for CI failure due to [this reason](https://github.com/EmbarkStudios/ash-molten/pull/38#issuecomment-735841817)

**Comment by MarnixKuijs** [comment]
@XAMPPRocky now that #38 is submitted which included a fix for your current problem the CI should be able to pass if you get latest on your branch

**Comment by lpil** [comment]
Thanks @MarnixKuijs , I'll take over as Erin is on holiday

**Review by MaikKlein — APPROVED** [review]

**Pull request merged**
