### PR TITLE
Release 0.8.1+1.1.1#4a0a5cd

### PR DESCRIPTION
**Pull request by VZout**
Updated MoltenVK to commit hash `4a0a5cd`

Fixes https://github.com/EmbarkStudios/ash-molten/issues/44

### CODE REVIEW

**Comment by VZout** [comment]
Built on top of https://github.com/EmbarkStudios/ash-molten/pull/43 but should be ready for review.

**Comment by VZout** [comment]
nvm lets test rust-shaders first.

**Comment by VZout** [comment]
Minor issue solved. Ark now works out of the box with rust-shaders on m1 mac if you use this branch as patch.

**Review by repi — APPROVED** [review]
Sweet, nice work!

**Comment by repi** [comment]
Some CI problems, but otherwise this seems to work well so let's get this merged in and publish a new release!

**Review by MaikKlein — APPROVED** [review]

**Comment by VZout** [comment]
Outdated by https://github.com/EmbarkStudios/ash-molten/pull/47

**Pull request closed without merging**
