### PR TITLE
Update careers link

### PR DESCRIPTION
**Pull request by lpil**
The current URL points to the old website and is invalid

### CODE REVIEW

**Comment by lpil** [comment]
Not sure what `Error: could not find native static library `MoltenVK`, perhaps an -L flag is missing?` means on CI

**Comment by MaikKlein** [comment]
Uhm I haven't touched ash-molten in a while. Not sure what is going on without investigating. Main seems to be green, so maybe something in the build script is failing?

Only the pre-built step is failing it seems https://github.com/EmbarkStudios/ash-molten/blob/main/build.rs#L228 Maybe something is wrong with the download. I wonder why there are no logs :(

**Comment by MaikKlein** [comment]
Maybe @MarnixKuijs knows more

**Comment by MarnixKuijs** [comment]
Interesting, I thought I fixed that bug. I will look into it.

**Comment by MarnixKuijs** [comment]
Right... I was afraid of this, for some reason the CI can't find the lib on the first run of the CI for a specific pull request.  When running the CI again it will pass all the steps just fine.

**Comment by MarnixKuijs** [comment]
Okay I'm severely confused. Apparently verbose output results in the build passing?

**Comment by MaikKlein** [comment]
> Okay I'm severely confused. Apparently verbose output results in the build passing?

Could be a temporary fluke while downloading. Maybe we should run with verbose all the time on the ci?

**Comment by MarnixKuijs** [comment]
> Maybe we should run with verbose all the time on the ci?
Yeah I think that is best. Are we doing this through this PR or make a sperate one for clarity sake?

**Comment by MaikKlein** [comment]
> Yeah I think that is best. Are we doing this through this PR or make a sperate one for clarity sake?

yeah lets do a new PR for it

**Comment by lpil** [comment]
Can I merge this as the breakage is unrelated to this documentation change?

**Comment by repi** [comment]
Sure let's do it

**Comment by lpil** [comment]
Ta!

**Pull request merged**
