### PR TITLE
Upgrade to MoltenVK 1.0.38 and Xcode 11

### PR DESCRIPTION
**Pull request by repi**
[Release notes](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.38)

### CODE REVIEW

**Comment by MaikKlein** [comment]
Seems like we need to upgrade travis or switch to actions.

**Comment by repi** [comment]
This looks like issue #4 of potentially that the new MoltenVK doesn't support older Xcode 10.3 (which we use and still need to use). Did retry building MoltenVK locally now again with Xcode 10.3 and get the same issue, will file a issue with them and ask

**Comment by repi** [comment]
Turns out MoltenVK indeed requires Xcode 11 now, I'll upgrade the CI in the PR here

**Comment by repi** [comment]
Hmm no compile errors now, but some fairly cryptic link errors instead.

```
 = note: Undefined symbols for architecture x86_64:

            "_OBJC_CLASS_$_CAEDRMetadata", referenced from:

                objc-class-ref in libMoltenVK.a(libMoltenVK.a-x86_64-master.o)
```

**Comment by MaikKlein** [comment]
This is defined in core animation https://developer.apple.com/documentation/quartzcore/caedrmetadata?language=objc we just need to link with it.

**Comment by MaikKlein** [comment]
Wait quartzcore includes core animation which we already link with.

**Comment by repi** [comment]
Hmm I got a different build error when building this branch with Xcode 11 locally:

```
xcodebuild -quiet -project "MoltenVKPackaging.xcodeproj" -scheme "MoltenVK Package (macOS only)" build
still building MoltenVK
clang: error: no such file or directory: '11.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk'
clang: error: no such file or directory: '11.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks'
clang: error: no such file or directory: '11.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib'
clang: warning: no such sysroot directory: '/Applications/Xcode' [-Wmissing-sysroot]
note: Using new build systemnote: Planning buildnote: Constructing build description
```

**Comment by repi** [comment]
This builds locally for me with Xcode 11.1. Did notice that Travis was building on an older Mac OS 10.14.4 but with bleeding edge Xcode 11.2 beta so that could be the cause of the problem and linking error potentially.

Will switch it to Xcode 11.1

**Comment by repi** [comment]
Nope some error still with Xcode 11.1 on Travis

**Comment by Jake-Shadle** [comment]
Can't fail on travis if you remove travis!

**Comment by repi** [comment]
Oh noes failed on GitHub Actions also, well at least it is failing faster now. in 15 min instead of 37. so that is some type of progress.

GitHub Actions is also building with Mac OS 10.14 (Mojave) and not 10.15 (Catalina), no option to change or configure.

**Comment by repi** [comment]
GitHub plans to roll out Mac 10.15 (Catalina) within 2 weeks: https://github.com/actions/virtual-environments/issues/53

So if that is the error then this could be resolved then soon. And right now we don't have an urgent need for this and it is critical that CI works so can just wait.

**Comment by repi** [comment]
Yay now compiles with Mac OS 10.15 (Catalina) that GitHub Actions just switched to!

**Pull request merged**
